Vagrant.configure("2") do |config|
  N = 3

  (1..N).each do |machine_id|
    config.vm.define "tsvm#{machine_id}" do |machine|
      machine.vm.box = "ubuntu/jammy64"
      machine.vm.hostname = "tsvm#{machine_id}"
      machine.vm.network :private_network, ip: "192.168.56.#{10+machine_id}"
    end
  end
end
